# Generated by Django 2.1.4 on 2019-02-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='minuto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
