# Generated by Django 2.1.4 on 2019-02-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0003_auto_20190209_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='studente',
            name='goals',
            field=models.IntegerField(default=0),
        ),
    ]
